<%@ include file="top.inc"%>

<div id="ggfooter">
	<p class="author alignright">
		<a href="http://validator.w3.org/check?uri=referer">
			<img src="<jtien:templateResource item="/${templateName}/css/images/valid-xhtml11.png"/>" alt="Valid XHTML 1.1" style="width:88px; height:31px" />
		</a>
		<a href="http://jigsaw.w3.org/css-validator/check/referer">
			<img src="<jtien:templateResource item="/${templateName}/css/images/vcss.gif"/>" alt="Valid CSS!" style="width:88px; height:31px" />
		</a>
	</p>
	<p class="copyright alignleft">SpringNet Project (v1.0.1). <a href="https://github.com/lilylnx/cncaptech/" title="https://github.com/lilylnx/cncaptech/"><abbr>Open Source.</abbr></a></p>
	<div class="clear"></div>
</div>