<%@ include file="top.inc"%>

<script type="text/javascript">$('body').addClass('gg-admin');</script>
<div id="globalTop" class="fixed_elem">
	<div id="ggadminbar">
		<ul>
			<li class="selected"><span>Administrator</span></li>
		</ul>
	</div>
	<div id="ggaction"><span class="one">Mantech Helpdesk</span></div>
	<div id="ggshadow"><div></div></div>
</div>
<div id="globalContainer">
	<%@ include file="gg_adminmenu.inc"%>