<%@ include file="top.inc"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript"><%@ include file="/_/default/__init.js"%></script>
<script type="text/javascript" src="<jtien:templateResource item="/jquery/jquery-1.6.4.js"/>"></script>
<script type="text/javascript" src="<jtien:templateResource item="/closure/goog/base.js"/>"></script>
<script type="text/javascript" src="<jtien:templateResource item="/default/__global_runonce.js"/>"></script>
<meta http-equiv="X-UA-Compatible" content="IE=9, IE=8, chrome=1" />
<meta http-equiv="Content-Type" content="text/html; charset=<jtien:settings key="encoding"/>" />
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta name="author" content="<jtien:settings key="author"/>" />
<meta name="keywords" content="<jtien:settings key="web.metatag.keywords"/>" />
<meta name="description" content="<jtien:settings key="web.metatag.description"/>" />
<base href="${contextPath}/" />
<link rel="shortcut icon" type="image/x-icon" href="<jtien:templateResource item="/${templateName}/css/images/favicon.ico"/>" />
<title><c:out value="${pageTitle}"><jtien:settings key="web.title"/></c:out></title>
</head>
<body class="">