<%@ include file="top.inc" %><compress:html jsCompressor="closure" compressJavaScript="true" compressCss="true" removeIntertagSpaces="true">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript"><%@ include file="/_/default/__init.js" %></script>
<script type="text/javascript" src="${contextPath}/_/jquery/jquery-1.6.4.js"></script>
<script type="text/javascript" src="${contextPath}/_/closure/goog/base.js"></script>
<script type="text/javascript" src="${contextPath}/_/default/__global_runonce.js"></script>
<meta http-equiv="X-UA-Compatible" content="IE=9, IE=8, chrome=1" />
<meta http-equiv="Content-Type" content="text/html; charset=${encoding}" />
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta name="keywords" content="${metaKeywords}" />
<meta name="description" content="${metaDescription}" />
<base href="${contextPath}/" />
<title>${pageTitle}</title>
</head>
<body>
</compress:html>