<%@ include file="top.inc" %><compress:html jsCompressor="closure" compressJavaScript="true" compressCss="true" removeIntertagSpaces="true">
<?xml version="1.0" encoding="${encoding}" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript" src="${contextPath}/_/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript"><%@ include file="/_/js/__global_runonce.js" %></script>
<meta http-equiv="X-UA-Compatible" content="IE=9, IE=8, chrome=1" />
<meta http-equiv="Content-Type" content="text/html; charset=${encoding}" />
<meta name="keywords" content="${metaKeywords}"/>
<meta name="description" content="${metaDescription}"/>
<base href="${contextPath}/" />
<title>${pageTitle}</title>
</head>
<body>
</compress:html>