<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@
taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %><%@
taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %><%@
taglib uri="http://www.springframework.org/tags/form" prefix="f" %><%@
taglib uri="http://htmlcompressor.googlecode.com/taglib/compressor" prefix="compress" %><%@
taglib uri="http://code.google.com/p/springnet" prefix="jtien" %>