<%@ include file="../layout/top.inc" %>

<style type="text/css">
  #ggabout {
    margin: 40px 20% 0;
    padding: 30px 0;
    text-align: center;
    background-color: rgba(255,255,255,.8);
    border: 1px solid #000;
  }
</style>
<div id="ggabout">
	<h1 style="margin:20px auto"><jtien:i18n key="Welcome.hello" /></h1>
	<div style="margin-top:30px">
		<p><jtien:i18n key="Project.hosting" /></p>
		<p><jtien:i18n key="Project.hosting.link" /></p>
	</div>
	<div style="margin:20px auto 10px">
		<p><jtien:i18n key="Project.libraries" /></p>
		<p><jtien:i18n key="Project.libraries.link1" /></p>
	</div>
	<div style="margin:20px auto 10px">
		<p><jtien:i18n key="Project.mirrors" /></p>
		<p><jtien:i18n key="Project.mirrors.link1" /><br /><jtien:i18n key="Project.mirrors.link2" /></p>
	</div>
</div>
