<div style="text-align:center">
	<h1 style="margin:20px auto">${welcomeMsg}</h1>
	<div style="margin-top:30px">
		<p>Project Hosting:</p>
		<p><a href="https://github.com/lilylnx/cncaptech/">github.com/lilylnx/cncaptech/</a></p>
	</div>
	<div style="margin:20px auto 10px">
		<p>Libraries:</p>
		<p><a href="http://repo.or.cz/w/libjcafe.git">repo.or.cz/w/libjcafe.git</a></p>
	</div>
	<div style="margin:20px auto 10px">
		<p>Mirrors:</p>
		<p><a href="http://code.google.com/p/springnet/">code.google.com/p/springnet/</a><br />
			<a href="http://www.assembla.com/spaces/cncaptech/">assembla.com/spaces/cncaptech/</a></p>
	</div>
	<a class="g-b g-b-r" href="${contextPath}/?p=login" style="margin:30px 0 0">ENTER LOGIN PAGE</a>
</div>