<%@ include file="../layout/top.inc" %>

<div style="text-align:center">
	<h1 style="margin:20px auto"><jtien:i18n key="Welcome.hello" /></h1>
	<div style="margin-top:30px">
		<p><jtien:i18n key="Project.hosting" /></p>
		<p><jtien:i18n key="Project.hosting.link" /></p>
	</div>
	<div style="margin:20px auto 10px">
		<p><jtien:i18n key="Project.libraries" /></p>
		<p><jtien:i18n key="Project.libraries.link1" /></p>
	</div>
	<div style="margin:20px auto 10px">
		<p><jtien:i18n key="Project.mirrors" /></p>
		<p><jtien:i18n key="Project.mirrors.link1" /><br /><jtien:i18n key="Project.mirrors.link2" /></p>
	</div>
</div>
