goog.require("goog.dom");goog.require("goog.editor.Command");goog.require("goog.editor.Field");goog.require("goog.editor.plugins.BasicTextFormatter");goog.require("goog.editor.plugins.EnterHandler");goog.require("goog.editor.plugins.HeaderFormatter");goog.require("goog.editor.plugins.LinkBubble");goog.require("goog.editor.plugins.LinkDialogPlugin");goog.require("goog.editor.plugins.ListTabHandler");goog.require("goog.editor.plugins.LoremIpsum");goog.require("goog.editor.plugins.RemoveFormatting");
goog.require("goog.editor.plugins.SpacesTabHandler");goog.require("goog.editor.plugins.UndoRedo");goog.require("goog.ui.Dialog");goog.require("goog.ui.editor.DefaultToolbar");goog.require("goog.ui.editor.ToolbarController");
var $dialogOpts={title:"Mantech Helpdesk",autoOpen:false,draggable:true,modal:true,resizable:false,position:"center",minWidth:390,minHeight:190,width:"auto",height:"auto",closeOnEscape:false,open:function(){$(".ui-dialog-titlebar-close").remove()},buttons:{Close:function(){$(this).dialog("destroy")}}},$validateOpts={debug:$debug,errorClass:"error",validClass:"valid",onkeyup:false,onfocusout:false,highlight:function(a,b,c){$(a).addClass(b).removeClass(c);$(a).next("span[class~="+a.id+"]").addClass(b)},
unhighlight:function(a,b,c){$(a).addClass(c).removeClass(b);$(a.form).find("span[class~="+a.id+"]").removeClass(b)}},$defaultDlgId="ajax-response",$adminMenu="#adminmenu";
$.ajaxSetup({scriptCharset:"UTF-8",statusCode:{400:function(){jTien.callJqDialog("ajax-response","The request cannot be fulfilled due to bad syntax.",{title:"HTTP Response 400"}).dialog("open")},404:function(){jTien.callJqDialog("ajax-response","The requested resource could not be found but may be available again in the future.",{title:"HTTP Response 404"}).dialog("open")},500:function(){jTien.callJqDialog("ajax-response","Internal Server Error. Please try again later.",{title:"HTTP Response 500"}).dialog("open")}}});
$.validator.setDefaults($validateOpts);$.validator.addMethod("vietnameseDate",function(a){return a.match(/^\d\d\d\d\/\d\d?\/\d\d?$/)},"Required yyyy/MM/dd.");ajaxPageload=function(){$.history.init(applyAjax_pageload,{unescape:"=/,;"})};applyAjax_pageload=function(a){a?jTien.ajaxFromLink(void 0,jTien.url("/loader"),"#ggbody-content").success(function(){applyAjax_pagelet()}):jTien.ajaxFromLink("#menu-dashboard a.gg-menu-top",jTien.url("/loader"),"#ggbody-content")};
applyAjax_adminmenu=function(){$("#adminmenu a").each(function(a,b){$(this).click(function(c){jTien.ajaxFromLink(this,jTien.url("/loader"),"#ggbody-content").success(function(){applyAjax_pagelet();currentMenuItem(a,b)});c.preventDefault();return false})})};
applyAjax_pagelet=function(){$(".g-pl a:not(.na,.ui-tabs li.ui-state-default a)").each(function(){$(this).click(function(a){jTien.ajaxFromLink(this,jTien.url("/loader"),"#ggbody-content").success(function(){applyAjax_pagelet()});a.preventDefault();return false})})};currentMenuItem=function(a,b){var c=$($adminMenu),h=$(b),d=h.parents("li.gg-menu-top");c.find(".current").removeClass("current");h.addClass("current");d.addClass("current");d.find("a.gg-menu-top").addClass("current")};
shakeContainer=function(a){jTien.toJqId(a).stop(true,true).effect("shake",{times:2,distance:5},50)};$(function(){jTien.f.autocompleteOff();jTien.f.completeFormAction();jTien.f.disableDrag('{"tags":["a", "img"], "classes":["g-b"]}');$.extend($.validator.messages,{required:"",minlength:"At least {0} characters.",maxlength:"Max {0} characters.",email:"eg, yourname@example.com",digit:"Must be a positive number.",equalTo:"Passwords do not match."});$(".ui-datepicker a").live("click",function(a){a.preventDefault()})});
String.prototype.endsWith=function(a){return this.indexOf(a,this.length-a.length)!==-1};
(function(a,b){var c=function(){return new c.fn.init};c.fn=c.prototype={init:function(){return{}}};c.fn.init.prototype=c.fn;c.toJqId=function(a){return typeof a==="string"?/^#/.test(a)?$(a):$("#"+a):a};c.url=function(a){return typeof a==="string"?$ctx.concat(a).concat($ext):$ctx};c.resetForm=function(a){a=c.toJqId(a);a[0].reset();a.find(":input[class!=noreset]:visible:enabled:first").focus();return a};c.ajaxSubmit=function(a){return c.f.ajaxSubmit(a)};c.ajaxConnect=function(a,d,f){d=d instanceof HTMLFormElement?
$(d):c.toJqId(d);return c.f.ajaxConnect(a,{async:false,type:d.attr("method"),url:d.attr("action"),data:f==b?d.serialize():f})};c.ajaxFromLink=function(a,b,f){return c.f.ajaxFromLink(a,b).success(function(a){c.toJqId(f).html(a);c.f.completeFormAction()})};c.callJqDialog=function(a,d,f,g){var e=c.f.isUrl(d);g==b&&(g=f,f=e?{}:b);if(typeof f==="object")f.async=false;d=e?$.ajax(d,f).responseText:'<p class="gg-popup-msg">'+d+"</p>";return c.f.createJqDialog(a,d,g)};c.adminMenu={init:function(){var a=$("#adminmenu");
$(".gg-menu-toggle",a).each(function(){var a=$(this),b=a.siblings(".gg-submenu");b.length?a.click(function(){c.adminMenu.toggle(b)}):a.hide()})},toggle:function(a){a.slideToggle(150,function(){var b=a.css("display","").parent().toggleClass("gg-menu-open").attr("id");b&&$("li.gg-has-submenu","#adminmenu").each(function(a,c){b==c.id&&$(c).hasClass("gg-menu-open")})});return false}};c.f=c.prototype={autocompleteOff:function(){$debug&&!isIEBrowser()&&console.log('Assigned autocomplete="off" on input[type=text].');
$("form.off").attr("autocomplete","off");$("input[type=text].off").attr("autocomplete","off")},completeFormAction:function(){$debug&&!isIEBrowser()&&console.log('Auto assigning "'+$ext+'" for form[action].');$("form").attr("action",function(){var a=$ctx+$(this).attr("action");return!a.endsWith("/")&&!a.endsWith($ext)?a+$ext:a})},disableDrag:function(a){a=$.parseJSON(a);$.each(a.tags,function(a,b){$debug&&!isIEBrowser()&&console.log('Diabled dragging on tag: "'+b+'"');$(b).live("mousedown",$false)});
$.each(a.classes,function(a,b){$debug&&!isIEBrowser()&&console.log('Diabled dragging on class: ".'+b+'"');$("."+b).live("mousedown",$false)})},getJSON:function(a){var b=null;$.ajax({url:$ctx+"/_/"+a,async:false,dataType:"json",success:function(a){b=a}});return b},ajaxSubmit:function(a){a=a instanceof HTMLFormElement?$(a):a;a={async:false,type:a.attr("method"),url:a.attr("action"),data:a.serialize()};return $.ajax(a)},ajaxConnect:function(a,d,f,g,e){if(c.f.isBlank(d))return null;typeof d==="object"?
(e=e||d,g=f=d=b):(d=c.f.isUrl(d)?d:b,f=!c.f.isBlank(f)?f:b,g=!c.f.isBlank(g)?g:"GET");e=e||{};e.async=e.async==b?false:e.async;e.url=d!=b?d:e.url;e.data=f!=b?f:e.data;e.type=e.type==b?g:e.type;d=$.ajax(e);c.toJqId(a).html(d.responseText);return d},ajaxFromLink:function(a,d,f){var a=(a==b?document.location.hash:c.f.isUrl(a)?a:$(a).attr("href")).replace(/^.*#/,""),g="q=".concat(a);f==b&&(f=d,d=b);d=$.ajax({async:false,url:f,type:d||"get",data:g,cache:false});$.history.load(a);return d},createJqDialog:function(a,
b,c){a=document.getElementById(a)==null?$('<div id="'+a+'"></div>'):$("#"+a);a.html(b);a.dialog($dialogOpts);typeof c==="object"&&a.dialog(c);return a},isBlank:function(a){return a==null||typeof a==="string"&&/^\s*$/.test(a)},isUrl:function(a){return a!=null&&typeof a==="string"&&/^(\/|http:\/\/|https:\/\/|ftp:\/\/)/.test(a)}};a.jTien=c})(window);
$(function(){$("body").hasClass("gg-admin")&&(ajaxPageload(),applyAjax_adminmenu(),applyAjax_pagelet(),jTien.adminMenu.init(),ggAdminBar_applyMenuPopup(),$("#lnkOptions").click(openOptionsPopup),$("#close-personal-menu").click(closePersonalMenu),$("#profile").click(profileHandler),$("#signout").click(signoutHandler),$("#new-complaint").click(openNewComplaintPage))});ggAdminBar_applyMenuPopup=function(){$("#ggadminbar li.gg-menupop").find(".ggl").each(function(){$(this).click(ggAdminBar_openMenuPopup)})};
ggAdminBar_openMenuPopup=function(){var a=$(this),b=a.parent(),c=a.siblings("div.gg-menupop");c.is(":hidden")&&(a.addClass("gg-menupop-open"),b.addClass("gg-menupop-open"),c.show("fast"));return false};ggAdminBar_closeMenuPopup=function(a){if(a.is(":visible")){var b=a.parents("li.gg-menupop-open");a.hide("fast");b.removeClass("gg-menupop-open");b.find(".gg-menupop-open").removeClass("gg-menupop-open")}};closePersonalMenu=function(){ggAdminBar_closeMenuPopup($("#gg-personal-menu"))};
openOptionsPopup=function(){jTien.callJqDialog("ajax-response","This function is temporarily not allowed. It will be released in version 2.0.").dialog("open");return false};profileHandler=function(){var a=jTien.url("/user")+"?action=profile",a=jTien.callJqDialog("userprofile-dialog",a,{title:"Mantech Profile",width:600,buttons:{}});$("#profile-tabs").tabs();jTien.f.completeFormAction();a.dialog("open");$("#close-personal-menu").click()};
signoutHandler=function(){var a=$(this).attr("href");jTien.callJqDialog("ajax-response","Please confirm the logout?",{title:"Logout Confirmation",buttons:{OK:function(){document.location=a},Cancel:function(){$(this).dialog("destroy");$("#close-personal-menu").click()}}}).dialog("open");return false};openNewComplaintPage=function(){$("#addcomplaint").click()};
buildJqDialogOpts=function(a,b){return{title:b,buttons:{OK:function(){a.valid()&&jTien.ajaxSubmit(a).success(function(b){jTien.callJqDialog($defaultDlgId,b.message,{buttons:{Close:function(){$(this).dialog("destroy")}}});b.name=="add"&&b.status=="1"&&jTien.resetForm(a)}).error(function(){$(this).dialog("destroy")})},Cancel:function(){$(this).dialog("destroy")}}}};
$("#pagelet_signin").ready(function(){$("#signin-form").delegate("#reset","click",function(){jTien.resetForm("#signin-form")});$("#signin-form").delegate("#signin","click",function(){$debug&&!isIEBrowser()&&console.log("#"+this.id+" button is clicked.");$("#signin-form").validate({rules:{id:{required:true,minlength:2},passwd:{required:true,minlength:1}},messages:{id:{required:"Enter your username or email.",minlength:"ID, at least {0} characters."},passwd:{required:"Enter your password.",minlength:"Password, at least {0} characters."}},
invalidHandler:function(){shakeContainer("#signin-box")},submitHandler:function(a){jTien.ajaxSubmit(a).success(function(a){a.status==1?document.location=jTien.url("/index"):jTien.callJqDialog("ajax-response",a.message,{buttons:{Close:function(){$(this).dialog("destroy");jTien.resetForm("#signin-form");$("#signin-form").submit()}}}).dialog("open")}).error(function(){jTien.resetForm("#signin-form")})}});$("#signin-form").submit();return false})});
$("#pagelet_signin #testZone").ready(function(){var a=null;$("#testZone").delegate("#test1","click",function(){a||(a=new goog.ui.Dialog);a.setTitle("I have an Iframe mask :)");a.setContent("Some windowed elements leak through standard divs so we add an iframe to mask the nasties.");a.setButtonSet(goog.ui.Dialog.ButtonSet.OK);a.setVisible(true)});$("#testZone").delegate("#test2","click",function(){var a=$ctx+"/user"+$ext,c=$.parseJSON('{"dlgConfirm": {"id": "dlg-confirm","title": "Display Users Confirmation","content": "Are you sure you want to show user list?"}}').dlgConfirm;
jTien.callJqDialog(c.id,c.content,{title:c.title,buttons:{OK:function(){jTien.callJqDialog(c.id,a)},Cancel:function(){$(this).dialog("destroy")}}}).dialog("open");return false})});
$(function(){_equipmentadd_btnAdd="#btnAdd";_equipmentadd_btnReset="#btnReset";_equipmentedit_btnEdit="#btnEdit";_complaintlist_filterForm="#complaint-filter-form";_complaintlist_filterSubmit="#filter-query-submit";_complaintlist_resultList="#the-list";_complaintadd_btnAdd="#btnAdd";_complaintadd_btnReset="#btnReset";_complaintedit_btnEdit="#btnEdit";_assignmentadd_btnAdd="#btnAdd";_assignmentadd_btnReset="#btnReset";$("#filter-query-submit","#pagelet_listuser").live("click",function(){jTien.ajaxConnect("#the-list",
"#user-filter-form").success(function(a){(a==null||a.length==0)&&$("#the-list").html('<tr><td colspan="9" style="padding-top:5px;text-align:center">No data to show.</td></tr>')})});$("#lnkShowAll","#pagelet_listuser").live("click",function(){jTien.ajaxConnect("#the-list","#user-filter-form","q=&f=0")});$("#btnAdd","#pagelet_adduser").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Add User Confirmation");a.validate({rules:{username:{required:true,minlength:3,maxlength:16},
passwd:{required:true,minlength:6},confirm_passwd:{required:true,equalTo:"#password"},email:{required:true,email:true},firstName:{required:true,minlength:1,maxlength:30},lastName:{required:true,minlength:1,maxlength:30},address:{required:true,minlength:1,maxlength:200}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,"Are you sure you want to add new user?",b).dialog("open")}});a.submit()});$("#btnReset","#pagelet_adduser").live("click",function(){jTien.resetForm($(this).parents("form"))});
$("#btnEdit","#pagelet_edituser").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Edit User Confirmation");a.validate({rules:{email:{required:true,email:true},address:{required:true,minlength:3,maxlength:200}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,"Are you sure you want to edit this user?",b).dialog("open")}});a.submit()});$("#btnAdd","#pagelet_addcategory").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Add category Confirmation");
a.validate({rules:{name:{required:true}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,"Are you sure you want to add new category?",b).dialog("open")}});a.submit()});$("#btnReset","#pagelet_addcategory").live("click",function(){jTien.resetForm($(this).parents("form"))});$("#btnEdit","#pagelet_editcategory").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Edit Category Confirmation");a.validate({rules:{name:{required:true}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,
"Are you sure want to edit this category?",b).dialog("open")}});a.submit()});$("#filter-query-submit","#pagelet_listequipment").live("click",function(){jTien.ajaxConnect("#the-list","#equipment-filter-form").success(function(a){(a==null||a.length==0)&&$("#the-list").html('<tr><td colspan="3" style="padding-top:5px;text-align:center">No data to show.</td></tr>')})});$(_equipmentadd_btnAdd,"#pagelet_addequipment").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Edit Equipment Confirmation");
a.validate({rules:{name:{required:true}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,"Are you sure you want to add new equipment?",b).dialog("open")}});a.submit()});$(_equipmentadd_btnReset,"#pagelet_addequipment").live("click",function(){jTien.resetForm($(this).parents("form"))});$(_equipmentedit_btnEdit,"#pagelet_editequipment").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Edit Category Confirmation");a.validate({rules:{name:{required:true}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,
"Are you sure want to edit this equipment?",b).dialog("open")}});a.submit()});$(_complaintlist_filterSubmit,"#pagelet_listcomplaint").live("click",function(){var a=$("#dateFrom").val().trim(),b=$("#dateTo").val().trim(),c=$("#status").val(),h=$("#priority").val(),a="q="+$("#query").val()+"&f="+$("#field-name").val()+(a.length!=0?"&dateFrom="+a:"")+(b.length!=0?"&dateTo="+b:"")+"&status="+c+"&priority="+h;jTien.ajaxConnect(_complaintlist_resultList,_complaintlist_filterForm,a).success(function(a){(a==
null||a.length==0)&&$(_complaintlist_resultList).html('<tr><td colspan="7">No data to show.</td></tr>')})});$(_complaintadd_btnAdd,"#pagelet_addcomplaint").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Add Complaint Confirmation");a.validate({rules:{complaint_title:{required:true},complaint_content:{required:true}},submitHandler:function(){jTien.callJqDialog($defaultDlgId,"Are you sure you want to add new complaint?",b).dialog("open")}});a.submit()});$(_complaintadd_btnReset,
"#pagelet_editcomplaint").live("click",function(){jTien.resetForm($(this).parents("form"))});$(_complaintedit_btnEdit,"#pagelet_editcomplaint").live("click",function(){var a=$(this).parents("form"),b=buildJqDialogOpts(a,"Edit Complaint Confirmation");a.validate({submitHandler:function(){jTien.callJqDialog($defaultDlgId,"Are you sure want to edit this complaint?",b).dialog("open")}});a.submit()});$(_assignmentadd_btnAdd,"#pagelet_addassignment").live("click",function(){var a=$(this).parents("form"),
b=buildjqDialogOpts(a,"Added assignment successfully.");a.validate({rules:{beginDate:{required:true,vietnameseDate:true},duration:{required:true,digits:true},userId:{required:true}},submitHandler:function(){jTien.callJqDialog($defaultDialogId,"Are you sure you want to add new assignment?",b).dialog("open")}});a.submit()});$(_assignmentadd_btnReset,"#pagelet_addassignment").live("click",function(){jTien.resetForm($(this).parents("form"))})});
startChart=function(){function a(a,b,c,d){g.xAxis[0].setCategories(b);g.series[0].remove();g.addSeries({name:a,data:c,color:d||"white"})}var b=[560,2E3,700,4E3],c=[100,200,30,130,60,30,10,100,600,200,100,50,150,800,200,100,30,70,80,20,200,200,1200,400,200,100,300,1600],h=c.slice(0,7),d=c.slice(7,14),f=c.slice(14,21),c=c.slice(21,28),g=0,e=Highcharts.getOptions().colors,i=["First Week","Second Week","Third Week","Fourth Week"],j=[{y:b[0],color:e[0],drilldown:{name:"First Week",categories:"Monday,Tuesday,Wednesday,Thurday,Friday,Saturday,Sunday".split(","),
data:h,color:e[0]}},{y:b[1],color:e[1],drilldown:{name:"Second Week",categories:"Monday,Tuesday,Wednesday,Thurday,Friday,Saturday,Sunday".split(","),data:d,color:e[1]}},{y:b[2],color:e[2],drilldown:{name:"Third Week",categories:"Monday,Tuesday,Wednesday,Thurday,Friday,Saturday,Sunday".split(","),data:f,color:e[2]}},{y:b[3],color:e[3],drilldown:{name:"Fourth Week",categories:"Monday,Tuesday,Wednesday,Thurday,Friday,Saturday,Sunday".split(","),data:c,color:e[3]}}],g=new Highcharts.Chart({credits:{enabled:false},
chart:{renderTo:"container",type:"column"},title:{text:"Daily, Weekly, Monthly Complaint Report"},subtitle:{text:"Click to the column to view details"},xAxis:{categories:i},yAxis:{title:{text:"Total Complaints"}},plotOptions:{column:{cursor:"pointer",point:{events:{click:function(){var b=this.drilldown;b?a(b.name,b.categories,b.data,b.color):a("Monthly Report",i,j)}}},dataLabels:{enabled:true,color:e[5],style:{fontweight:"bold"},formatter:function(){return this.y+" complaints"}}}},tooltip:{formatter:function(){var a=
this.point,b=this.x+":<b>"+this.y+" complaints</b><br/>";b+=a.drilldown?"Click to view "+a.category:"Click to return to browser brands";return b}},series:[{name:"Monthly Report",data:j,color:"white"}],exporting:{enabled:true}})};